//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Rogue {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureRogueText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureRogueText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Rogue.FeatureRogueText", typeof(FeatureRogueText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 4th level, and again at 8th, 10th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature..
        /// </summary>
        internal static string Ability_Score_Improvement {
            get {
                return ResourceManager.GetString("Ability Score Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 14th level, if you are able to hear, you are aware of the location of any hidden or invisible creature within 10 feet of you..
        /// </summary>
        internal static string Blindsense {
            get {
                return ResourceManager.GetString("Blindsense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 2nd level, your quick thinking and agility allow you to move and act quickly. You cantake a bonus action on each of your turns in combat. This action can be used only to take the Dash, Disengage, or Hide action..
        /// </summary>
        internal static string Cunning_Action {
            get {
                return ResourceManager.GetString("Cunning Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 18th level, you are so evasive that attackers rarely gain the upper hand against you. No attack roll has advantage against you while you aren’t incapacitated..
        /// </summary>
        internal static string Elusive {
            get {
                return ResourceManager.GetString("Elusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 7th level, you can nimbly dodge out of the way of certain area effects, such as a red dragon’s fiery breath or an ice storm spell. When you are subjected to an effect that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw, and only half damage if you fail..
        /// </summary>
        internal static string Evasion {
            get {
                return ResourceManager.GetString("Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 1st level, choose two of your skill proficiencies, or one of your skill proficiencies and your proficiency with thieves’ tools. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies.
        ///At 6th level, you can choose two more of your proficiencies (in skills or with thieves’ tools) to gain this benefit..
        /// </summary>
        internal static string Expertise {
            get {
                return ResourceManager.GetString("Expertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By 11th level, you have refined your chosen skills until they approach perfection. Whenever you make an ability check that lets you add your proficiency bonus, you can treat a d20 roll of 9 or lower as a 10..
        /// </summary>
        internal static string Reliable_Talent {
            get {
                return ResourceManager.GetString("Reliable Talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 3rd level, you choose an archetype that you emulate in the exercise of your rogue abilities, such as Thief. Your archetype choice grants you features at 3rd level and then again at 9th, 13th, and 17th level..
        /// </summary>
        internal static string Roguish_Archetype {
            get {
                return ResourceManager.GetString("Roguish Archetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By 15th level, you have acquired greater mental strength. You gain proficiency in Wisdom saving throws..
        /// </summary>
        internal static string Slippery_Mind {
            get {
                return ResourceManager.GetString("Slippery Mind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 1st level, you know how to strike subtly and exploit a foe’s distraction. Once per turn, you can deal an extra 1d6 damage to one creature you hit with an attack if you have advantage on the attack roll. The attack must use a finesse or a ranged weapon.
        ///You don’t need advantage on the attack roll if another enemy of the target is within 5 feet of it, that enemy isn’t incapacitated, and you don’t have disadvantage on the attack roll.
        ///The amount of the extra damage increases as you gain levels i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sneak_Attack {
            get {
                return ResourceManager.GetString("Sneak Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 20th level, you have an uncanny knack for succeeding when you need to. If your attack misses a target within range, you can turn the miss into a hit. Alternatively, if you fail an ability check, you can treat the d20 roll as a 20.
        ///Once you use this feature, you can’t use it again until you finish a short or long rest..
        /// </summary>
        internal static string Stroke_of_Luck {
            get {
                return ResourceManager.GetString("Stroke of Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During your rogue training you learned thieves’ cant, a secret mix of dialect, jargon, and code that allows you to hide messages in seemingly normal conversation. Only another creature that knows thieves’ cant understands such messages.It takes four times longer to convey such a message than it does to speak the same idea plainly.
        ///In addition, you understand a set of secret signs and symbols used to convey short, simple messages, such as whether an area is dangerous or the territory ofa thieves’ guild, whe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Thieves__Cant {
            get {
                return ResourceManager.GetString("Thieves\' Cant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 5th level, when an attacker that you can see hits you with an attack, you can use your reaction to halve the attack’s damage against you..
        /// </summary>
        internal static string Uncanny_Dodge {
            get {
                return ResourceManager.GetString("Uncanny Dodge", resourceCulture);
            }
        }
    }
}
