//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Ranger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureRangerText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureRangerText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Ranger.FeatureRangerText", typeof(FeatureRangerText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature..
        /// </summary>
        internal static string Ability_Score_Improvement {
            get {
                return ResourceManager.GetString("Ability Score Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn..
        /// </summary>
        internal static string Extra_Attack {
            get {
                return ResourceManager.GetString("Extra Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 1st level, you have significant experience studying, tracking, hunting, and even talking to a certain type of enemy.
        ///Choose a type of favored enemy: aberrations, beasts, celestials, constructs, dragons, elementals, fey, fiends, giants, monstrosities, oozes, plants, or undead. Alternatively, you can select two races of humanoid (such as gnolls and orcs) as favored enemies.
        ///You have advantage on Wisdom (Survival) checks to track your favored enemies, as well as on Intelligence checks to recall  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Favored_Enemy {
            get {
                return ResourceManager.GetString("Favored Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 18th level, you gain preternatural senses that help you fight creatures you can’t see. When you attack a creature you can’t see, your inability to see it doesn’t impose disadvantage on your attack rolls against it.
        ///You are also aware of the location of any invisible creature within 30 feet of you, provided that the creature isn’t hidden from you and you aren’t blinded or deafened..
        /// </summary>
        internal static string Feral_Senses {
            get {
                return ResourceManager.GetString("Feral Senses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 2nd level, you adopt a particular style of fighting as your specialty. Choose one of the following options. You can’t take a Fighting Style option more than once, even if you later get to choose again..
        /// </summary>
        internal static string Fighting_Style {
            get {
                return ResourceManager.GetString("Fighting Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 20th level, you become an unparalleled hunter of your enemies. Once on each of your turns, you can add your Wisdom modifier to the attack roll or the damage roll of an attack you make against one of your favored enemies. You can choose to use this feature before or after the roll, but before any effects of the roll are applied..
        /// </summary>
        internal static string Foe_Slayer {
            get {
                return ResourceManager.GetString("Foe Slayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 10th level, you can spend 1 minute creating camouflage for yourself. You must have access to fresh mud, dirt, plants, soot, and other naturally occurring materials with which to create your camouflage.
        ///Once you are camouflaged in this way, you can try to hide by pressing yourself up against a solid surface, such as a tree or wall, that is at least as tall and wide as you are. You gain a +10 bonus to Dexterity (Stealth) checks as long as you remain there without moving or taking actions. Once yo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hide_in_Plain_Sight {
            get {
                return ResourceManager.GetString("Hide in Plain Sight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 8th level, moving through nonmagical difficult terrain costs you no extra movement. You can also pass through nonmagical plants without being slowed by them and without taking damage from them if they have thorns, spines, or a similar hazard.
        ///In addition, you have advantage on saving throws against plants that are magically created or manipulated to impede movement, such those created by the entangle spell..
        /// </summary>
        internal static string Land_s_Stride {
            get {
                return ResourceManager.GetString("Land\'s Stride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are particularly familiar with one type of natural environment and are adept at traveling and surviving in such regions. Choose one type of favored terrain: arctic, coast, desert, forest, grassland, mountain, or swamp. When you make an Intelligence or Wisdom check related to your favored terrain, your proficiency bonus is doubled if you are using a skill that you’re proficient in.
        ///While traveling for an hour or more in your favored terrain, you gain the following benefits:
        /// • Difficult terrain doesn’t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Natural_Explorer {
            get {
                return ResourceManager.GetString("Natural Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 3rd level, you can use your action and expend one ranger spell slot to focus your awareness on the region around you. For 1 minute per level of the spell slot you expend, you can sense whether the following types of creatures are present within 1 mile of you (or within up to 6 miles if you are in your favored terrain): aberrations, celestials, dragons, elementals, fey, fiends, and undead. This feature doesn’t reveal the creatures’ location or number..
        /// </summary>
        internal static string Primeval_Awareness {
            get {
                return ResourceManager.GetString("Primeval Awareness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 3rd level, you choose an archetype that you strive to emulate, such as the Hunter. Your choice grants you features at 3rd level and again at 7th, 11th, and 15th level..
        /// </summary>
        internal static string Ranger_Archetype {
            get {
                return ResourceManager.GetString("Ranger Archetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By the time you reach 2nd level, you have learned touse the magical essence of nature to cast spells, much as a druid does.
        ///
        /// Spell Slots
        ///The Ranger table shows how many spell slots you have to cast your spells of 1st level and higher. To cast one of these spells, you must expend a slot of the spell’s level or higher. You regain all expended spell slots when you finish a long rest.
        ///For example, if you know the 1st-level spell animal friendship and have a 1st-level and a 2nd-level spell slot available, y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spellcasting {
            get {
                return ResourceManager.GetString("Spellcasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 14th level, you can use the Hide action as a bonus action on your turn. Also, you can’t be tracked by nonmagical means, unless you choose to leave a trail..
        /// </summary>
        internal static string Vanish {
            get {
                return ResourceManager.GetString("Vanish", resourceCulture);
            }
        }
    }
}
