//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Bard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureBardText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureBardText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Bard.FeatureBardText", typeof(FeatureBardText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature..
        /// </summary>
        internal static string Ability_Score_Improvement {
            get {
                return ResourceManager.GetString("Ability Score Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 3rd level, you delve intothe advanced techniques of a bard college of your choice. Your choice grants you features at 3rd level and again at 6th and 14th level..
        /// </summary>
        internal static string Bard_College {
            get {
                return ResourceManager.GetString("Bard College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can inspire others through stirring words or music. To do so, you use a bonus action on your turn to choose one creature other than yourself within 60 feet of you who can hear you. That creature gains one Bardic Inspiration die, a d6.
        ///Once within the next 10 minutes, the creature can roll the die and add the number rolled to one ability check, attack roll, or saving throw it makes. The creature can wait until afterit rolls the d20 before deciding to use the Bardic Inspiration die, but must decide befor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bardic_Inspiration {
            get {
                return ResourceManager.GetString("Bardic Inspiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 6th level, you gain the ability to use musical notes or words of power to disrupt mind-influencing effects. As an action, you can start a performance that lasts until the end of your next turn. During that time, you and any friendly creatures within 30 feet of you have advantage on saving throws against being frightened or charmed. A creature must be able to hear you to gain this benefit. Theperformance ends early if you are incapacitated or silenced or if you voluntarily end it (no action required)..
        /// </summary>
        internal static string Countercharm {
            get {
                return ResourceManager.GetString("Countercharm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 3rd level, choose two of your skill proficiencies. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies.
        ///At 10th level, you can choose another two skill proficiencies to gain this benefit..
        /// </summary>
        internal static string Expertise {
            get {
                return ResourceManager.GetString("Expertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning when you reach 5th level, you regain all of your expended uses of Bardic Inspiration when you finish a short or long rest..
        /// </summary>
        internal static string Font_of_Inspiration {
            get {
                return ResourceManager.GetString("Font of Inspiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 2nd level, you can add half your proficiency bonus, rounded down, to any ability check you make that doesn’t already include your proficiency bonus..
        /// </summary>
        internal static string Jack_of_All_Trades {
            get {
                return ResourceManager.GetString("Jack of All Trades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By 10th level, you have plundered magical knowledge from a wide spectrum of disciplines. Choose two spells from any class, including this one. A spell you choose must be of a level you can cast, as shown on the Bard table, or a cantrip.
        ///The chosen spells count as bard spells for you and are included in the number in the Spells Known column of the Bard table.
        ///You learn two additional spells from any class at 14th level and again at 18th level..
        /// </summary>
        internal static string Magical_Secrets {
            get {
                return ResourceManager.GetString("Magical Secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 2nd level, you can use soothing music or oration to help revitalize your wounded allies during a short rest. If you or any friendly creatures who can hear your performance regain hit points at the end of the short rest by spending one or more Hit Dice, each of those creatures regains an extra 1d6 hit points.
        ///The extra hit points increase when you reach certain levels in this class: to 1d8 at 9th level, to 1d10 at 13th level, and to 1d12 at 17th level..
        /// </summary>
        internal static string Song_of_Rest {
            get {
                return ResourceManager.GetString("Song of Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have learned to untangle and reshape the fabric of reality in harmony withyour wishes and music. Your spells are part of your vast repertoire, magic that you can tune to different situations.
        ///
        /// Cantrips
        ///You know two cantrips of your choice from the bard spell list. You learn additional bard cantrips of your choice at higher levels, as shown in the Cantrips Known column of the Bard table.
        ///
        /// Spell Slots
        ///The Bard table shows how many spell slots you have to cast your spells of 1st level and higher. T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spellcasting {
            get {
                return ResourceManager.GetString("Spellcasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 20th level, when you roll initiative and have no uses of Bardic Inspiration left, you regain one use..
        /// </summary>
        internal static string Superior_Inspiration {
            get {
                return ResourceManager.GetString("Superior Inspiration", resourceCulture);
            }
        }
    }
}
