//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Spells {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpellDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpellDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Spells.SpellDescriptions", typeof(SpellDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next turn. On a miss, the arrow splashes the target with acid for half as much of the initial damage and no damage at the end of its next turn..
        /// </summary>
        internal static string AcidArrow {
            get {
                return ResourceManager.GetString("AcidArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage.
        ///This spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6)..
        /// </summary>
        internal static string AcidSplash {
            get {
                return ResourceManager.GetString("AcidSplash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target’s hit point maximum and current hit points increase by 5 for the duration..
        /// </summary>
        internal static string Aid {
            get {
                return ResourceManager.GetString("Aid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You set an alarm against unwanted intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a Tiny or larger creature touches or enters the warded area. When you cast the spell, you can designate creatures that won’t set off the alarm. You also choose whether the alarm is mental or audible.
        ///A mental alarm alerts you with a ping in your mind if you are within 1 mile of the warded area. This ping awakens you if you ar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You assume a different form. When you cast the spell, choose one of the following options, the effects of which last for the duration of the spell. While the spell lasts, you can end one option as an action to gain the benefitsof a different one.
        ///    Aquatic Adaptation. You adapt your body to an aquatic environment, sprouting gills and growing webbing between your fingers. You can breathe underwater and gain a swimming speed equal to your walking speed.
        ///    Change Appearance. You transform your appearance [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AlterSelf {
            get {
                return ResourceManager.GetString("AlterSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This spell lets you convince a beast that you mean it no harm. Choose a beast that you can see within range. It must see and hear you. If the beast&apos;s Intelligence is 4 or higher, the spell fails. Otherwise, the beast must succeed on a Wisdom saving throw or be charmed by you for the spell&apos;s duration. If you or one of your companions harms the target, the spells ends..
        /// </summary>
        internal static string AnimalFirendship {
            get {
                return ResourceManager.GetString("AnimalFirendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By means of this spell, you use an animal to deliver a message. Choose a Tiny beast you can see within range, such as a squirrel, a blue jay, or a bat. You specify a location, which you must have visited, and a recipient who matches a general description, such as “a man or woman dressed in the uniform of the town guard” or “a red-haired dwarf wearing a pointed hat.” You also speak a message of up to twenty-five words. The target beast travels for the duration of the spell toward the specified location, cove [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnimalMessenger {
            get {
                return ResourceManager.GetString("AnimalMessenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your magic turns others into beasts. Choose any number of willing creatures that you can see within range. You transform each target into the form of a Large or smaller beast with a challenge rating of 4 or lower. On subsequent turns, you can use your action to transform affected creatures into new forms.
        ///The transformation lasts for the duration for each target, or until the target drops to 0 hit points or dies. You can choose a different form for each target. A target’s game statistics are replaced by th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnimalShapes {
            get {
                return ResourceManager.GetString("AnimalShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range. Your spell imbues the target witha foul mimicry of life, raising it as an undead creature. The target becomes a skeleton if you chose bones or Not for resale. Permission granted to print or photocopy this document for personal use only.System Reference Document 5.1116a zombie if you chose a corpse (the GM has the creature’s game statistics).
        ///On each of your turns, you can use a bonus action  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnimateDead {
            get {
                return ResourceManager.GetString("AnimateDead", resourceCulture);
            }
        }
    }
}
