//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.Race {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RacialFeatures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RacialFeatures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.Race.RacialFeatures", typeof(RacialFeatures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Strength score increases by 2, and your Charisma score increases by 1..
        /// </summary>
        internal static string Ability_Score_Increase_Dragonborn {
            get {
                return ResourceManager.GetString("Ability Score Increase Dragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Constitution score increases by 2..
        /// </summary>
        internal static string Ability_Score_Increase_Dwarf {
            get {
                return ResourceManager.GetString("Ability Score Increase Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Dexterity score increases by 2..
        /// </summary>
        internal static string Ability_Score_Increase_Elf {
            get {
                return ResourceManager.GetString("Ability Score Increase Elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Intelligence score increases by 2..
        /// </summary>
        internal static string Ability_Score_Increase_Gnome {
            get {
                return ResourceManager.GetString("Ability Score Increase Gnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Dexterity score increases by 2..
        /// </summary>
        internal static string Ability_Score_Increase_Halfling {
            get {
                return ResourceManager.GetString("Ability Score Increase Halfling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Intelligence score increases by 1..
        /// </summary>
        internal static string Ability_Score_Increase_High_Elf {
            get {
                return ResourceManager.GetString("Ability Score Increase High Elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Wisdom score increases by 1..
        /// </summary>
        internal static string Ability_Score_Increase_Hill_Dwarf {
            get {
                return ResourceManager.GetString("Ability Score Increase Hill Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ability scores each increase by 1..
        /// </summary>
        internal static string Ability_Score_Increase_Human {
            get {
                return ResourceManager.GetString("Ability Score Increase Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Charisma score increases by 1..
        /// </summary>
        internal static string Ability_Score_Increase_Lightfoot_Halfling {
            get {
                return ResourceManager.GetString("Ability Score Increase Lightfoot Halfling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Constitution score increases by 1..
        /// </summary>
        internal static string Ability_Score_Increase_Rock_Gnome {
            get {
                return ResourceManager.GetString("Ability Score Increase Rock Gnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whenever you make an Intelligence (History) check related to magic items, alchemical objects, or technological devices, you can add twice your proficiency bonus, instead of any proficiency bonus you normally apply..
        /// </summary>
        internal static string Artificer_s_Lore {
            get {
                return ResourceManager.GetString("Artificer\'s Lore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have advantage on saving throws against being frightened..
        /// </summary>
        internal static string Brave {
            get {
                return ResourceManager.GetString("Brave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation.\nWhen you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Breath_Weapon {
            get {
                return ResourceManager.GetString("Breath Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to exhale destructive energy. Because of your black draconic ancestry, the exhalation is a 5 by 30ft. line dealing Acid damgage.\nWhen you use your breath weapon, each creature in the area of the exhalation must make a Dexterity saving throw. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th level,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Breath_Weapon_Black {
            get {
                return ResourceManager.GetString("Breath Weapon Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to exhale destructive energy. Because of your blue draconic ancestry, the exhalation is a 5 by 30ft. line dealing Lightning damgage.\nWhen you use your breath weapon, each creature in the area of the exhalation must make a Dexterity saving throw. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th lev [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Breath_Weapon_Blue {
            get {
                return ResourceManager.GetString("Breath Weapon Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to exhale destructive energy. Because of your brass draconic ancestry, the exhalation is a 5 by 30ft. line dealing Fire damgage.\nWhen you use your breath weapon, each creature in the area of the exhalation must make a Dexterity saving throw. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th level,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Breath_Weapon_Brass {
            get {
                return ResourceManager.GetString("Breath Weapon Brass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to exhale destructive energy. Because of your bronze draconic ancestry, the exhalation is a 5 by 30ft. line dealing Lightning damgage.\nWhen you use your breath weapon, each creature in the area of the exhalation must make a Dexterity saving throw. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Breath_Weapon_Bronze {
            get {
                return ResourceManager.GetString("Breath Weapon Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to exhale destructive energy. Because of your copper draconic ancestry, the exhalation is a 5 by 30ft. line dealing Acid damgage.\nWhen you use your breath weapon, each creature in the area of the exhalation must make a Dexterity saving throw. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th level, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Breath_Weapon_Copper {
            get {
                return ResourceManager.GetString("Breath Weapon Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to exhale destructive energy. Because of your gold draconic ancestry, the exhalation is a 15 ft. cone dealing Fire damgage.\nWhen you use your breath weapon, each creature in the area of the exhalation must make a Dexterity saving throw. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th level, and 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Breath_Weapon_Gold {
            get {
                return ResourceManager.GetString("Breath Weapon Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to exhale destructive energy. Because of your green draconic ancestry, the exhalation is a 15 ft. cone dealing Poison damgage.\nWhen you use your breath weapon, each creature in the area of the exhalation must make a Constitution saving throw. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th level, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Breath_Weapon_Green {
            get {
                return ResourceManager.GetString("Breath Weapon Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to exhale destructive energy. Because of your red draconic ancestry, the exhalation is a 15 ft. cone dealing Fire damgage.\nWhen you use your breath weapon, each creature in the area of the exhalation must make a Dexterity saving throw. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th level, and 5d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Breath_Weapon_Red {
            get {
                return ResourceManager.GetString("Breath Weapon Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to exhale destructive energy. Because of your silver draconic ancestry, the exhalation is a 15 ft. cone dealing Cold damgage.\nWhen you use your breath weapon, each creature in the area of the exhalation must make a Constitution saving throw. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th level,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Breath_Weapon_Silver {
            get {
                return ResourceManager.GetString("Breath Weapon Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to exhale destructive energy. Because of your white draconic ancestry, the exhalation is a 15 ft. cone dealing Cold damgage.\nWhen you use your breath weapon, each creature in the area of the exhalation must make a Constitution saving throw. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th level, a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Breath_Weapon_White {
            get {
                return ResourceManager.GetString("Breath Weapon White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know one cantrip of your choice from the wizard spell list. Intelligence is your spellcasting ability for it..
        /// </summary>
        internal static string Cantrip {
            get {
                return ResourceManager.GetString("Cantrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have resistance to the damage type associated with your draconic ancestry..
        /// </summary>
        internal static string Damage_Resistance {
            get {
                return ResourceManager.GetString("Damage Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have resistance to Acid damage..
        /// </summary>
        internal static string Damage_Resistance_Black {
            get {
                return ResourceManager.GetString("Damage Resistance Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have resistance to Lightning damage..
        /// </summary>
        internal static string Damage_Resistance_Blue {
            get {
                return ResourceManager.GetString("Damage Resistance Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have resistance to Fire damage..
        /// </summary>
        internal static string Damage_Resistance_Brass {
            get {
                return ResourceManager.GetString("Damage Resistance Brass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have resistance to Lightning damage..
        /// </summary>
        internal static string Damage_Resistance_Bronze {
            get {
                return ResourceManager.GetString("Damage Resistance Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have resistance to Acid damage..
        /// </summary>
        internal static string Damage_Resistance_Copper {
            get {
                return ResourceManager.GetString("Damage Resistance Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have resistance to Fire damage..
        /// </summary>
        internal static string Damage_Resistance_Gold {
            get {
                return ResourceManager.GetString("Damage Resistance Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have resistance to Poison damage..
        /// </summary>
        internal static string Damage_Resistance_Green {
            get {
                return ResourceManager.GetString("Damage Resistance Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have resistance to Fire damage..
        /// </summary>
        internal static string Damage_Resistance_Red {
            get {
                return ResourceManager.GetString("Damage Resistance Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have resistance to Cold damage..
        /// </summary>
        internal static string Damage_Resistance_Silver {
            get {
                return ResourceManager.GetString("Damage Resistance Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have resistance to Cold damage..
        /// </summary>
        internal static string Damage_Resistance_White {
            get {
                return ResourceManager.GetString("Damage Resistance White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray..
        /// </summary>
        internal static string Darkvision_Dwarf {
            get {
                return ResourceManager.GetString("Darkvision Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accustomed to twilit forests and the night sky, you have superior vision in dark and dim conditions. Youcan see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray..
        /// </summary>
        internal static string Darkvision_Elf {
            get {
                return ResourceManager.GetString("Darkvision Elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accustomed to life underground,you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray..
        /// </summary>
        internal static string Darkvision_Gnome {
            get {
                return ResourceManager.GetString("Darkvision Gnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have advantage on saving throws against poison, and you have resistance against poison damage..
        /// </summary>
        internal static string Dwarven_Resilience {
            get {
                return ResourceManager.GetString("Dwarven Resilience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hit point maximum increases by 1, and it increases by 1 every time you gain a level..
        /// </summary>
        internal static string Dwarven_Toughness {
            get {
                return ResourceManager.GetString("Dwarven Toughness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have advantage on saving throws against being charmed, and magic can’t put you to sleep..
        /// </summary>
        internal static string Fey_Ancestry {
            get {
                return ResourceManager.GetString("Fey Ancestry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have advantage on all Intelligence, Wisdom, and Charisma saving throws against magic..
        /// </summary>
        internal static string Gnome_Cunning {
            get {
                return ResourceManager.GetString("Gnome Cunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can move through the space of any creature that is of a size larger than yours..
        /// </summary>
        internal static string Halfling_Nimbleness {
            get {
                return ResourceManager.GetString("Halfling Nimbleness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you roll a 1 on the d20 for an attack roll, ability check, or saving throw, you can reroll the die and must use the new roll..
        /// </summary>
        internal static string Lucky {
            get {
                return ResourceManager.GetString("Lucky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can attempt to hide even when you are obscured only by a creature that is at least one size larger than you..
        /// </summary>
        internal static string Naturally_Stealthy {
            get {
                return ResourceManager.GetString("Naturally Stealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus to the check, instead of your normal proficiency bonus..
        /// </summary>
        internal static string Stonecunning {
            get {
                return ResourceManager.GetString("Stonecunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have proficiency with artisan’s tools (tinker’s tools). Using those tools, you can spend 1 hour and 10 gp worth of materials to construct a Tiny clockwork device (AC 5, 1 hp). The device ceases to function after 24 hours (unless you spend 1 hour repairing it to keep the device functioning), or when you use your action to dismantle it; at that time, you can reclaim the materials used to create it. You can have up to three such devices active at a time.\nWhen you create a device, choose one of the followi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tinker {
            get {
                return ResourceManager.GetString("Tinker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elves don’t need to sleep. Instead, they meditate deeply, remaining semiconscious, for 4 hours a day. (The Common word for such meditation is “trance.”) While meditating, you can dream after a fashion; such dreams are actually mental exercises that have become reflexive through years of practice. After resting in this way, you gain the same benefit that a human does from 8 hours of sleep..
        /// </summary>
        internal static string Trance {
            get {
                return ResourceManager.GetString("Trance", resourceCulture);
            }
        }
    }
}
