//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.Race {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RacialFeatures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RacialFeatures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.Race.RacialFeatures", typeof(RacialFeatures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Constitution score increases by 2..
        /// </summary>
        internal static string Ability_Score_Increase_Dwarf {
            get {
                return ResourceManager.GetString("Ability Score Increase Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Wisdom score increases by 1..
        /// </summary>
        internal static string Ability_Score_Increase_Hill_Dwarf {
            get {
                return ResourceManager.GetString("Ability Score Increase Hill Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ability scores each increase by 1..
        /// </summary>
        internal static string Ability_Score_Increase_Human {
            get {
                return ResourceManager.GetString("Ability Score Increase Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray..
        /// </summary>
        internal static string Darkvision_Dwarf {
            get {
                return ResourceManager.GetString("Darkvision Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have advantage on saving throws against poison, and you have resistance against poison damage..
        /// </summary>
        internal static string Dwarven_Resilience {
            get {
                return ResourceManager.GetString("Dwarven Resilience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hit point maximum increases by 1, and it increases by 1 every time you gain a level..
        /// </summary>
        internal static string Dwarven_Toughness {
            get {
                return ResourceManager.GetString("Dwarven Toughness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus to the check, instead of your normal proficiency bonus..
        /// </summary>
        internal static string Stonecunning {
            get {
                return ResourceManager.GetString("Stonecunning", resourceCulture);
            }
        }
    }
}
