//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Paladin.OathOfDevotion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeaturePaladinOathOfDevotionText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeaturePaladinOathOfDevotionText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Paladin.OathOfDevotion.FeaturePaladinOathOf" +
                            "DevotionText", typeof(FeaturePaladinOathOfDevotionText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 7th level, you and friendly creatures within 10 feet of you can’t be charmed while you are conscious.
        ///At 18th level, the range of this aura increases to 30 feet..
        /// </summary>
        internal static string Aura_of_Devotion {
            get {
                return ResourceManager.GetString("Aura of Devotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you take this oath at 3rd level, you gain the following two Channel Divinity options.
        /// Sacred Weapon. As an action, you can imbue one weapon that you are holding with positive energy, using your Channel Divinity. For 1 minute, you add your Charisma modifier to attack rolls made with that weapon (with a minimum bonus of +1). The weapon also emits bright light in a 20-foot radius and dim light 20 feet beyond that. If the weapon is not already magical, it becomes magical for the duration.
        ///You can end th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Channel_Divinity {
            get {
                return ResourceManager.GetString("Channel Divinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 20th level, as an action, you can emanate an aura of sunlight. For 1 minute, bright light shines from you in a 30-foot radius, and dim light shines 30 feet beyond that.
        ///Whenever an enemy creature starts its turn in the bright light, the creature takes 10 radiant damage.
        ///In addition, for the duration, you have advantage on saving throws against spells cast by fiends or undead.
        ///Once you use this feature, you can’t use it again until you finish a long rest..
        /// </summary>
        internal static string Holy_Nimbus {
            get {
                return ResourceManager.GetString("Holy Nimbus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Oath of Devotion binds a paladin to the loftiest ideals of justice, virtue, and order. Sometimes called cavaliers, white knights, or holy warriors, these paladins meet the ideal of the knight in shining armor, acting with honor in pursuit of justice and the greater good. They hold themselves to the highest standards of conduct, and some, for better or worse, hold the rest of the world to the same standards. Many who swear this oath are devoted to gods of law and good and use their gods’ tenets as the me [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oath_of_Devotion {
            get {
                return ResourceManager.GetString("Oath of Devotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 15th level, you are always under the effects of a protection from evil and good spell..
        /// </summary>
        internal static string Purity_of_Spirit {
            get {
                return ResourceManager.GetString("Purity of Spirit", resourceCulture);
            }
        }
    }
}
