//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Wizard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureWizardText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureWizardText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Wizard.FeatureWizardText", typeof(FeatureWizardText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature..
        /// </summary>
        internal static string Ability_Score_Improvement {
            get {
                return ResourceManager.GetString("Ability Score Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have learned to regain some of your magical energy by studying your spellbook. Once per day when you finish a short rest, you can choose expended spell slots to recover. The spell slots can have a combined level that is equal to or less than half your wizard level (rounded up), and none of the slots can be 6th level or higher.
        ///For example, if you’re a 4th-level wizard, you can recover up to two levels worth of spell slots. You can recover either a 2nd-level spell slot or two 1st-level spell slots..
        /// </summary>
        internal static string Arcane_Recovery {
            get {
                return ResourceManager.GetString("Arcane Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 2nd level, you choose an arcane tradition, shaping your practice of magic through one of eight schools.
        ///Your choice grants you features at 2nd level and again at 6th, 10th, and 14th level..
        /// </summary>
        internal static string Arcane_Tradition {
            get {
                return ResourceManager.GetString("Arcane Tradition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 20th level, you gain mastery over two powerful spells and can cast them with little effort. Choose two 3rd-level wizard spells in your spellbook as your signature spells. You always have these spells prepared, they don’t count against the number of spells you have prepared, and you can cast each of them once at 3rd level without expending a spell slot. When you do so, you can’t do so again until you finish a short or long rest.
        ///If you want to cast either spell at a higher level, you must exp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Signature_Spells {
            get {
                return ResourceManager.GetString("Signature Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 18th level, you have achieved such mastery over certain spells that you can cast them at will. Choose a 1st-level wizard spell and a 2nd-level wizard spell that are in your spellbook. You can cast those spells at their lowest level without expending a spell slot when you have them prepared. If you want to cast either spell at a higher level, you must expend a spell slot as normal.
        ///By spending 8 hours in study, you can exchange one or both of the spells you chose for different spells of the same levels..
        /// </summary>
        internal static string Spell_Mastery {
            get {
                return ResourceManager.GetString("Spell Mastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a student of arcane magic, you have a spellbook containing spells that show the first glimmerings of your true power.
        ///
        /// Cantrips
        ///At 1st level, you know three cantrips of your choice from the wizard spell list. You learn additional wizard cantrips of your choice at higher levels, as shown in the Cantrips Known column of the Wizard table.
        ///
        /// Spellbook
        ///At 1st level, you have a spellbook containing six 1st-level wizard spells of your choice. Your spellbook is the repository of the wizard spells you know [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spellcasting {
            get {
                return ResourceManager.GetString("Spellcasting", resourceCulture);
            }
        }
    }
}
