//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Fighter.Champion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureFighterChampionText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureFighterChampionText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Fighter.Champion.FeatureFighterChampionText" +
                            "", typeof(FeatureFighterChampionText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 10th level, you can choose a second option from the Fighting Style class feature..
        /// </summary>
        internal static string Additional_Fighting_Style {
            get {
                return ResourceManager.GetString("Additional Fighting Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archetypal Champion focuses on the development of raw physical power honed to deadly perfection. Those who model themselves on this archetype combine rigorous training with physical excellence to deal devastating blows..
        /// </summary>
        internal static string Champion {
            get {
                return ResourceManager.GetString("Champion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning when you choose this archetype at 3rd level, your weapon attacks score a critical hit on a roll of 19 or 20..
        /// </summary>
        internal static string Improved_Critical {
            get {
                return ResourceManager.GetString("Improved Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 7th level, you can add half your proficiency bonus (round up) to any Strength, Dexterity, or Constitution check you make that doesn’t already use your proficiency bonus.
        ///In addition, when you make a running long jump, the distance you can cover increases by a number of feet equal to your Strength modifier..
        /// </summary>
        internal static string Remarkable_Athlete {
            get {
                return ResourceManager.GetString("Remarkable Athlete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 15th level, your weapon attacks score a critical hit on a roll of 18–20..
        /// </summary>
        internal static string Superior_Critical {
            get {
                return ResourceManager.GetString("Superior Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 18th level, you attain the pinnacle of resilience in battle. At the start of each of your turns, you regain hit points equal to 5 + your Constitution modifier if you have no more than half of your hit points left. You don’t gain this benefit if you have 0 hit points..
        /// </summary>
        internal static string Survivor {
            get {
                return ResourceManager.GetString("Survivor", resourceCulture);
            }
        }
    }
}
