//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Monk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureMonkText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureMonkText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Monk.FeatureMonkText", typeof(FeatureMonkText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature..
        /// </summary>
        internal static string Ability_Score_Improvement {
            get {
                return ResourceManager.GetString("Ability Score Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 3rd level, you can use your reaction to deflect or catch the missile when you are hit by a ranged weapon attack. When you do so, the damage you take from the attack is reduced by 1d10 + your Dexterity modifier + your monk level.
        ///If you reduce the damage to 0, you can catch the missile if it is small enough for you to hold in one hand and you have at least one hand free. If you catch a missile in this way, you can spend 1 ki point to make a ranged attack with the weapon or piece of ammunition yo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Deflect_Missiles {
            get {
                return ResourceManager.GetString("Deflect Missiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 14th level, your mastery of ki grants you proficiency in all saving throws.
        ///Additionally, whenever you make a saving throw and fail, you can spend 1 ki point to reroll it and take the second result..
        /// </summary>
        internal static string Diamond_Soul {
            get {
                return ResourceManager.GetString("Diamond Soul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 18th level, you can use your action to spend 4 ki points to become invisible for 1 minute. During that time, you also have resistance to all damage but force damage.
        ///Additionally, you can spend 8 ki points to cast the astral projection spell, without needing material components. When you do so, you can’t take any other creatures with you..
        /// </summary>
        internal static string Empty_Body {
            get {
                return ResourceManager.GetString("Empty Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 7th level, your instinctive agility lets you dodge out of the way of certain area effects, such as a blue dragon’s lightning breath or a fireball spell. When you are subjected to an effect that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw, and only half damage if you fail..
        /// </summary>
        internal static string Evasion {
            get {
                return ResourceManager.GetString("Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn..
        /// </summary>
        internal static string Extra_Attack {
            get {
                return ResourceManager.GetString("Extra Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 2nd level, your training allows you to harness the mystic energy of ki. Your access to this energy is represented by a number of ki points. Your monk level determines the number of points you have, as shown in the Ki Points column of the Monk table.
        ///You can spend these points to fuel various ki features. You start knowing three such features: Flurry of Blows, Patient Defense, and Step of the Wind. You learn more ki features as you gain levels in this class.
        ///When you spend a ki point, it is una [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ki {
            get {
                return ResourceManager.GetString("Ki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 6th level, your unarmed strikes count as magical forthe purpose of overcoming resistance and immunity to nonmagical attacks and damage..
        /// </summary>
        internal static string Ki_Empowered_Strikes {
            get {
                return ResourceManager.GetString("Ki-Empowered Strikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 1st level, your practice of martial arts gives you mastery of combat styles that use unarmed strikes and monk weapons, which are shortswords and any simple melee weapons that don’t have the two-handed or heavy property.
        ///You gain the following benefits while you are unarmed or wielding only monk weapons and you aren’t wearing armor or wielding a shield:
        /// • You can use Dexterity instead of Strength for the attack and damage rolls of your unarmed strikes and monk weapons.
        /// • You can roll a d4 in place of [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Martial_Arts {
            get {
                return ResourceManager.GetString("Martial Arts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 3rd level, you commit yourself to a monastic tradition. Your tradition grants you features at 3rd level and again at 6th, 11th, and 17th level..
        /// </summary>
        internal static string Monastic_Tradition {
            get {
                return ResourceManager.GetString("Monastic Tradition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 20th level, when you roll for initiative and have no ki points remaining, you regain 4 ki points..
        /// </summary>
        internal static string Perfect_Self {
            get {
                return ResourceManager.GetString("Perfect Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 10th level, your mastery of the ki flowing through you makes you immune to disease and poison..
        /// </summary>
        internal static string Purity_of_Body {
            get {
                return ResourceManager.GetString("Purity of Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 4th level, you can use your reaction when you fall to reduce any falling damage you take by an amount equal to five times your monk level..
        /// </summary>
        internal static string Slow_Fall {
            get {
                return ResourceManager.GetString("Slow Fall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 7th level, you can use your action to end one effect on yourself that is causing you to be charmed or frightened..
        /// </summary>
        internal static string Stillness_of_Mind {
            get {
                return ResourceManager.GetString("Stillness of Mind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 5th level, you can interfere with the flow of ki in an opponent’s body. When you hit another creature with a melee weapon attack, you can spend 1 ki point to attempt a stunning strike. The target must succeed on a Constitution saving throw or be stunned until the end of your next turn..
        /// </summary>
        internal static string Stunning_Strike {
            get {
                return ResourceManager.GetString("Stunning Strike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 15th level, your ki sustains you so that you suffer none of the frailty of old age, and you can’t be aged magically. You can still die of old age, however. In addition, you no longer need food or water..
        /// </summary>
        internal static string Timeless_Body {
            get {
                return ResourceManager.GetString("Timeless Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 13th level, you learn to touch the ki of other minds so that you understand all spoken languages. Moreover, any creature that can understand a language can understand what you say..
        /// </summary>
        internal static string Tongue_of_the_Sun_and_Moon {
            get {
                return ResourceManager.GetString("Tongue of the Sun and Moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 1st level, while you are wearing no armor and not wielding a shield, your AC equals 10 + your Dexterity modifier + your Wisdom modifier..
        /// </summary>
        internal static string Unarmored_Defense {
            get {
                return ResourceManager.GetString("Unarmored Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 2nd level, your speed increases by 10 feet while you are not wearing armor or wielding a shield. This bonus is increased to 15 feet at 6th level, 20 feet at 10th level, 25 feet at 14th level, and 30 feet at 18th level.
        ///At 9th level, you gain the ability to move along vertical surfaces and across liquids on your turn without falling during the move..
        /// </summary>
        internal static string Unarmored_Movement {
            get {
                return ResourceManager.GetString("Unarmored Movement", resourceCulture);
            }
        }
    }
}
