//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Warlock.EldritchInvocations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EldritchInvocationsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EldritchInvocationsText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Warlock.EldritchInvocations.EldritchInvocat" +
                            "ionsText", typeof(EldritchInvocationsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you cast eldritch blast, add your Charisma modifier to the damage it deals on a hit..
        /// </summary>
        internal static string Agonizing_Blast {
            get {
                return ResourceManager.GetString("Agonizing Blast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast mage armor on yourself at will, without expending a spell slot or material components..
        /// </summary>
        internal static string Armor_of_Shadows {
            get {
                return ResourceManager.GetString("Armor of Shadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast levitate on yourself at will, without expending a spell slot or material components..
        /// </summary>
        internal static string Ascendant_Step {
            get {
                return ResourceManager.GetString("Ascendant Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast speak with animals at will, without expending a spell slot..
        /// </summary>
        internal static string Beast_Speech {
            get {
                return ResourceManager.GetString("Beast Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gain proficiency in the Deception and Persuasion skills..
        /// </summary>
        internal static string Beguiling_Influence {
            get {
                return ResourceManager.GetString("Beguiling Influence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast compulsion once using a warlock spell slot. You can’t do so again until you finish a long rest..
        /// </summary>
        internal static string Bewitching_Whispers {
            get {
                return ResourceManager.GetString("Bewitching Whispers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now inscribe magical rituals in your Book of Shadows. Choose two 1st-level spells that have the ritual tag from any class’s spell list (the two needn’t be from the same list). The spells appear in the book and don’t count against the number of spells you know. With your Book of Shadows in hand, you can cast the chosen spells as rituals. You can’t cast the spells except as rituals, unless you’ve learned them by some other means. You can also cast a warlock spell you know as a ritual if it has the rit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Book_of_Ancient_Secrets {
            get {
                return ResourceManager.GetString("Book of Ancient Secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast hold monsterat will—targeting a celestial, fiend, or elemental—without expending a spell slot or material components. You must finish a long rest before you can use this invocation on the same creature again..
        /// </summary>
        internal static string Chains_of_Carceri {
            get {
                return ResourceManager.GetString("Chains of Carceri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see normally in darkness, both magical and nonmagical, to a distance of 120 feet..
        /// </summary>
        internal static string Devil_s_Sight {
            get {
                return ResourceManager.GetString("Devil\'s Sight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast confusiononce using a warlock spell slot. You can’t do so again until you finish a long rest..
        /// </summary>
        internal static string Dreadful_Word {
            get {
                return ResourceManager.GetString("Dreadful Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast detect magic at will, without expending a spell slot..
        /// </summary>
        internal static string Eldritch_Sight {
            get {
                return ResourceManager.GetString("Eldritch Sight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you cast eldritch blast, its range is 300 feet..
        /// </summary>
        internal static string Eldritch_Spear {
            get {
                return ResourceManager.GetString("Eldritch Spear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can read all writing..
        /// </summary>
        internal static string Eyes_of_the_Rune_Keeper {
            get {
                return ResourceManager.GetString("Eyes of the Rune Keeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast false life on yourself at will as a 1st-level spell, without expending a spell slot or material components..
        /// </summary>
        internal static string Fiendish_Vigor {
            get {
                return ResourceManager.GetString("Fiendish Vigor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to touch a willing humanoid and perceive through its senses until the end of your next turn. As long as the creature is on the same plane of existence as you, you can use your action on subsequent turns to maintain this connection, extending the duration until the end of your next turn. While perceiving through the other creature’s senses, you benefit from any special senses possessed by that creature, and you areblinded and deafened to your own surroundings..
        /// </summary>
        internal static string Gaze_of_Two_Minds {
            get {
                return ResourceManager.GetString("Gaze of Two Minds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you hit a creature with your pact weapon, the creature takes extra necrotic damage equal to your Charisma modifier (minimum 1)..
        /// </summary>
        internal static string Lifedrinker {
            get {
                return ResourceManager.GetString("Lifedrinker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast disguise self at will, without expending a spell slot..
        /// </summary>
        internal static string Mask_of_Many_Faces {
            get {
                return ResourceManager.GetString("Mask of Many Faces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast alter selfat will, without expending a spell slot..
        /// </summary>
        internal static string Master_of_Myriad_Forms {
            get {
                return ResourceManager.GetString("Master of Myriad Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast conjure elemental once using a warlock spell slot. You can’t do so again until you finish a long rest..
        /// </summary>
        internal static string Minions_of_Chaos {
            get {
                return ResourceManager.GetString("Minions of Chaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast slowonce using a warlock spell slot. You can’t do so again until you finish a long rest..
        /// </summary>
        internal static string Mire_the_Mind {
            get {
                return ResourceManager.GetString("Mire the Mind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast silent image at will, without expending a spell slot or material components..
        /// </summary>
        internal static string Misty_Visions {
            get {
                return ResourceManager.GetString("Misty Visions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you are in an area of dim light or darkness, you can use your action to become invisible until you move or take an action or areaction..
        /// </summary>
        internal static string One_with_Shadows {
            get {
                return ResourceManager.GetString("One with Shadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast jumpon yourself at will, without expending a spell slot or material components..
        /// </summary>
        internal static string Otherworldy_Leap {
            get {
                return ResourceManager.GetString("Otherworldy Leap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you hit a creature with eldritch blast, you can push the creature up to 10 feet away from you in a straight line..
        /// </summary>
        internal static string Repelling_Blast {
            get {
                return ResourceManager.GetString("Repelling Blast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast polymorph once using a warlock spell slot. You can’t do so again until you finish a long rest..
        /// </summary>
        internal static string Sculptor_of_Flesh {
            get {
                return ResourceManager.GetString("Sculptor of Flesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast bestow curse once using a warlock spell slot. You can’t do so again until you finish a long rest..
        /// </summary>
        internal static string Sign_of_Ill_Omen {
            get {
                return ResourceManager.GetString("Sign of Ill Omen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast baneonce using a warlock spell slot. You can’t do so again until you finish a long rest..
        /// </summary>
        internal static string Thief_of_Five_Fates {
            get {
                return ResourceManager.GetString("Thief of Five Fates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can attack with your pact weapon twice, instead of once, whenever you take the Attack action on your turn..
        /// </summary>
        internal static string Thirsting_Blade {
            get {
                return ResourceManager.GetString("Thirsting Blade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast arcane eyeat will, without expending a spell slot..
        /// </summary>
        internal static string Visions_of_Distant_Realms {
            get {
                return ResourceManager.GetString("Visions of Distant Realms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can communicate telepathically with your familiar and perceive through your familiar’s senses as long as you are on the same plane of existence.
        ///Additionally, while perceiving through your familiar’s senses, you can also speak through your familiar in your own voice, even if your familiar is normally incapable of speech..
        /// </summary>
        internal static string Voice_of_the_Chain_Master {
            get {
                return ResourceManager.GetString("Voice of the Chain Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast speak with dead at will, without expending a spell slot..
        /// </summary>
        internal static string Whispers_of_the_Grave {
            get {
                return ResourceManager.GetString("Whispers of the Grave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see the true form of any shapechanger or creature concealed by illusion or transmutation magic while the creature is within 30 feet of you and within line of sight..
        /// </summary>
        internal static string Witch_Sight {
            get {
                return ResourceManager.GetString("Witch Sight", resourceCulture);
            }
        }
    }
}
