//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Warlock.EldritchInvocations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EldritchInvocationsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EldritchInvocationsText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Warlock.EldritchInvocations.EldritchInvocat" +
                            "ionsText", typeof(EldritchInvocationsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you cast eldritch blast, add your Charisma modifier to the damage it deals on a hit..
        /// </summary>
        internal static string Agonizing_Blast {
            get {
                return ResourceManager.GetString("Agonizing Blast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast mage armor on yourself at will, without expending a spell slot or material components.
        ///
        /// Mage Armor
        ///1st-level abjuration
        ///Casting Time: 1 action
        ///Range: Touch
        ///Components: V, S
        ///Duration: 8 hours
        ///
        ///If you are not wearing armor, a protective magical force surrounds you until the spell ends. Your base AC becomes 13 + your Dexterity modifier. The spell ends if you don armor or if you dismiss the spell as an action..
        /// </summary>
        internal static string Armor_of_Shadows {
            get {
                return ResourceManager.GetString("Armor of Shadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast levitate on yourself at will, without expending a spell slot or material components.
        ///
        /// Levitate
        ///2nd-level transmutation
        ///Casting Time: 1 action
        ///Range: Self
        ///Components: V, S
        ///Duration: Concentration, up to 10 minutes
        ///
        ///You rise vertically, up to 20 feet, and remains suspended there for the duration. You can move only by pushing or pulling against a fixed object or surface within reach (such as a wall or a ceiling), which allows you to move as if you were climbing. You can move up or down a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ascendant_Step {
            get {
                return ResourceManager.GetString("Ascendant Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast speak with animals at will, without expending a spell slot.
        ///
        /// Speak with Animals
        ///1st-level divination
        ///Casting Time: 1 action
        ///Range: Self
        ///Components: V, S
        ///Duration: 10 minutes
        ///
        ///You gain the ability to comprehend and verbally communicate with beasts for the duration. The knowledge and awareness of many beasts is limited by their intelligence, but at minimum, beasts can give you information about nearby locations and monsters, including whatever they can perceive or have perceived within  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Beast_Speech {
            get {
                return ResourceManager.GetString("Beast Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gain proficiency in the Deception and Persuasion skills..
        /// </summary>
        internal static string Beguiling_Influence {
            get {
                return ResourceManager.GetString("Beguiling Influence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast compulsion once using a warlock spell slot. You can&apos;t do so again until you finish a long rest.
        ///
        /// Compulsion
        ///4th-level enchantment
        ///Casting Time: 1 action
        ///Range: 30 feet
        ///Components: V, S
        ///Duration: Concentration, up to 1 minute
        ///
        ///Creatures of your choice that you can see within range and that can hear you must make a Wisdom saving throw. A target automatically succeeds on this saving throw if it can&apos;t be charmed. On a failed save, a target is affected by this spell. Until the spell ends,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bewitching_Whispers {
            get {
                return ResourceManager.GetString("Bewitching Whispers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now inscribe magical rituals in your Book of Shadows. Choose two 1st-level spells that have the ritual tag from any class’s spell list (the two needn’t be from the same list). The spells appear in the book and don’t count against the number of spells you know. With your Book of Shadows in hand, you can cast the chosen spells as rituals. You can’t cast the spells except as rituals, unless you’ve learned them by some other means. You can also cast a warlock spell you know as a ritual if it has the rit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Book_of_Ancient_Secrets {
            get {
                return ResourceManager.GetString("Book of Ancient Secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast hold monster at will—targeting a celestial, fiend, or elemental—without expending a spell slot or material components. You must finish a long rest before you can use this invocation on the same creature again.
        ///
        /// Hold Monster
        ///5th-level enchantment
        ///Casting Time: 1 action
        ///Range: 90 feet
        ///Components: V, S
        ///Duration: Concentration, up to 1 minute
        ///
        ///Choose a celestial, fiend, or elemental that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the dur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chains_of_Carceri {
            get {
                return ResourceManager.GetString("Chains of Carceri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see normally in darkness, both magical and nonmagical, to a distance of 120 feet..
        /// </summary>
        internal static string Devil_s_Sight {
            get {
                return ResourceManager.GetString("Devil\'s Sight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast confusion once using a warlock spell slot. You can&apos;t do so again until you finish a long rest.
        ///
        /// Confusion
        ///4th-level enchantment
        ///Casting Time: 1 action
        ///Range: 90 feet
        ///Components: V, S, M (three nut shells)
        ///Duration: Concentration, up to 1 minute
        ///
        ///This spell assaults and twists creatures&apos; minds, spawning delusions and provoking uncontrolled action. Each creature in a 10-foot-radius sphere centered on a point you choose within range must succeed on a Wisdom saving throw when you cast thi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dreadful_Word {
            get {
                return ResourceManager.GetString("Dreadful Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast detect magic at will, without expending a spell slot.
        ///
        /// Detect Magic
        ///1st-level divination
        ///Casting Time: 1 action
        ///Range: Self
        ///Components: V, S
        ///Duration: Concentration, up to 10 minutes
        ///
        ///For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any.
        ///The spell can penetrate most barriers, but i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eldritch_Sight {
            get {
                return ResourceManager.GetString("Eldritch Sight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you cast eldritch blast, its range is 300 feet..
        /// </summary>
        internal static string Eldritch_Spear {
            get {
                return ResourceManager.GetString("Eldritch Spear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can read all writing..
        /// </summary>
        internal static string Eyes_of_the_Rune_Keeper {
            get {
                return ResourceManager.GetString("Eyes of the Rune Keeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast false life on yourself at will as a 1st-level spell, without expending a spell slot or material components.
        ///
        /// False Life
        ///1st-level necromancy
        ///Casting Time: 1 action
        ///Range: Self
        ///Components: V, S, M (a small amount of alcohol or distilled spirits)
        ///Duration: 1 hour
        ///
        ///Bolstering yourself with a necromantic facsimile of life, you gain 1d4 + 4 temporary hit points for the duration..
        /// </summary>
        internal static string Fiendish_Vigor {
            get {
                return ResourceManager.GetString("Fiendish Vigor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to touch a willing humanoid and perceive through its senses until the end of your next turn. As long as the creature is on the same plane of existence as you, you can use your action on subsequent turns to maintain this connection, extending the duration until the end of your next turn. While perceiving through the other creature’s senses, you benefit from any special senses possessed by that creature, and you areblinded and deafened to your own surroundings..
        /// </summary>
        internal static string Gaze_of_Two_Minds {
            get {
                return ResourceManager.GetString("Gaze of Two Minds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you hit a creature with your pact weapon, the creature takes extra necrotic damage equal to your Charisma modifier (minimum 1)..
        /// </summary>
        internal static string Lifedrinker {
            get {
                return ResourceManager.GetString("Lifedrinker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast disguise self at will, without expending a spell slot.
        ///
        /// Disguise Self
        ///1st-level illusion
        ///Casting Time: 1 action
        ///Range: Self
        ///Components: V, S
        ///Duration: 1 hour
        ///
        ///You make yourself—including your clothing, armor, weapons, and other belongings on your person—look different until the spell ends or until you use your action to dismiss it. You can seem 1 foot shorter or taller and can appear thin, fat, or in between. You can&apos;t change your body type, so you must adopt a form that has the same  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mask_of_Many_Faces {
            get {
                return ResourceManager.GetString("Mask of Many Faces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast alter self at will, without expending a spell slot.
        ///
        /// Alter Self
        ///2nd-level transmutation
        ///Casting Time: 1 action
        ///Range: Self
        ///Components: V, S
        ///Duration: Concentration, up to 1 hour
        ///
        ///You assume a different form. When you cast the spell, choose one of the following options, the effects of which last for the duration of the spell. While the spell lasts, you can end one option as an action to gain the benefits of a different one.
        /// Aquatic Adaptation. You adapt your body to an aquatic enviro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Master_of_Myriad_Forms {
            get {
                return ResourceManager.GetString("Master of Myriad Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast conjure elemental once using a warlock spell slot. You can&apos;t do so again until you finish a long rest.
        ///
        /// Conjure Elemental
        ///5th-level conjuration
        ///Casting Time: 1 minute
        ///Range: 90 feet
        ///Components: V, S, M (burning incense for air, soft clay for earth, sulfur and phosphorus for fire, or water and sand for water)
        ///Duration: Concentration, up to 1 hour
        ///
        ///You call forth an elemental servant. Choose an area of air, earth, fire, or water that fills a 10-foot cube within range. An elemental of ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Minions_of_Chaos {
            get {
                return ResourceManager.GetString("Minions of Chaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast slow once using a warlock spell slot. You can&apos;t do so again until you finish a long rest.
        ///
        /// Slow
        ///3rd-level transmutation
        ///Casting Time: 1 action
        ///Range:120 feet
        ///Components:V, S, M (a drop of molasses)
        ///Duration:Concentration, up to 1 minute
        ///
        ///You alter time around up to six creatures of your choice in a 40-foot cube within range. Each target must succeed on a Wisdom saving throw or be affected by this spell for the duration.
        ///An affected target&apos;s speed is halved, it takes a −2 penalty to A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mire_the_Mind {
            get {
                return ResourceManager.GetString("Mire the Mind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast silent image at will, without expending a spell slot or material components.
        ///
        /// Silent Image
        ///1st-level illusion
        ///Casting Time: 1 action
        ///Range: 60 feet
        ///Components: V, S
        ///Duration: Concentration, up to 10 minutes
        ///
        ///You create the image of anobject, a creature, or some other visible phenomenon that is no larger than a 15-foot cube. The image appears at a spot within range and lasts for the duration. The image is purely visual; it isn&apos;t accompanied by sound, smell, or other sensory effects.
        ///Y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Misty_Visions {
            get {
                return ResourceManager.GetString("Misty Visions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you are in an area of dim light or darkness, you can use your action to become invisible until you move or take an action or areaction..
        /// </summary>
        internal static string One_with_Shadows {
            get {
                return ResourceManager.GetString("One with Shadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast jump on yourself at will, without expending a spell slot or material components.
        ///
        /// Jump
        ///1st-level transmutation
        ///Casting Time: 1 action
        ///Range: Self
        ///Components: V, S
        ///Duration: 1 minute
        ///
        ///Your jump distance is tripled until the spell ends..
        /// </summary>
        internal static string Otherworldy_Leap {
            get {
                return ResourceManager.GetString("Otherworldy Leap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you hit a creature with eldritch blast, you can push the creature up to 10 feet away from you in a straight line..
        /// </summary>
        internal static string Repelling_Blast {
            get {
                return ResourceManager.GetString("Repelling Blast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast polymorph once using a warlock spell slot. You can&apos;t do so again until you finish a long rest.
        ///
        /// Polymorph
        ///4th-level transmutation
        ///Casting Time: 1 action
        ///Range: 60 feet
        ///Components: V, S, M (a caterpillar cocoon)
        ///Duration: Concentration, up to 1 hour
        ///
        ///This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. The spell has no effect on a shapechanger or a creature with 0 hit points.
        ///The tran [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sculptor_of_Flesh {
            get {
                return ResourceManager.GetString("Sculptor of Flesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast bestow curse once using a warlock spell slot. You can&apos;t do so again until you finish a long rest.
        ///
        /// Bestow Curse
        ///3rd-level necromancy
        ///Casting Time: 1 action
        ///Range: Touch
        ///Components: V, S
        ///Duration: Concentration, up to 1 minute
        ///You touch a creature, and that creature must succeed on a Wisdom saving throw or become cursed for the duration of the spell. 
        ///
        ///When you cast this spell, choose the nature of the curse from the following options:
        /// • Choose one ability score. While cursed, the t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sign_of_Ill_Omen {
            get {
                return ResourceManager.GetString("Sign of Ill Omen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast bane once using a warlock spell slot. You can’t do so again until you finish a long rest.
        ///
        /// Bane
        ///1st-level enchantment
        ///Casting Time: 1 action
        ///Range: 30 feet
        ///Components: V, S, M (a drop of blood)
        ///Duration: Concentration, up to 1 minute
        ///
        ///Up to three creatures of your choice that you can see within range must make Charisma saving throws. Whenever a target that fails this saving throw makes an attack roll or a saving throw before the spell ends, the target must roll a d4 and subtract the n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Thief_of_Five_Fates {
            get {
                return ResourceManager.GetString("Thief of Five Fates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can attack with your pact weapon twice, instead of once, whenever you take the Attack action on your turn..
        /// </summary>
        internal static string Thirsting_Blade {
            get {
                return ResourceManager.GetString("Thirsting Blade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast arcane eyeat will, without expending a spell slot.
        ///
        /// Arcane Eye
        ///4th-level divination
        ///Casting Time :1 action
        ///Range: 30 feet
        ///Components: V, S, M (a bit of bat fur)
        ///Duration: Concentration, up to 1 hour
        ///
        ///You create an invisible, magical eye within range that hovers in the air for the duration.
        ///You mentally receive visual information from the eye, which has normal vision and darkvision out to 30 feet. The eye can look in every direction.
        ///As an action, you can move the eye up to 30 feet i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Visions_of_Distant_Realms {
            get {
                return ResourceManager.GetString("Visions of Distant Realms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can communicate telepathically with your familiar and perceive through your familiar’s senses as long as you are on the same plane of existence.
        ///Additionally, while perceiving through your familiar’s senses, you can also speak through your familiar in your own voice, even if your familiar is normally incapable of speech..
        /// </summary>
        internal static string Voice_of_the_Chain_Master {
            get {
                return ResourceManager.GetString("Voice of the Chain Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cast speak with dead at will, without expending a spell slot.
        ///
        /// Speak with Dead
        ///3rd-level necromancy
        ///Casting Time: 1 action
        ///Range: 10 feet
        ///Components: V, S, M (burning incense)
        ///Duration: 10 minutes
        ///
        ///You grant the semblance of life and intelligence to a corpse of your choice within range, allowing it to answer the questions you pose. The corpse must still have a mouth and can&apos;t be undead. The spell fails if the corpse was the target of this spell within the last 10 days.
        ///Until the spell end [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Whispers_of_the_Grave {
            get {
                return ResourceManager.GetString("Whispers of the Grave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see the true form of any shapechanger or creature concealed by illusion or transmutation magic while the creature is within 30 feet of you and within line of sight..
        /// </summary>
        internal static string Witch_Sight {
            get {
                return ResourceManager.GetString("Witch Sight", resourceCulture);
            }
        }
    }
}
