//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Armor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArmorDescriptionText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArmorDescriptionText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Armor.ArmorDescriptionText", typeof(ArmorDescriptionText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This armor consists of a fitted metal chest piece worn with supple leather. Although it leaves the legs and arms relatively unprotected, this armor provides good protection for the wearer’s vital organs while leaving the wearer relatively unencumbered..
        /// </summary>
        internal static string Breastplate {
            get {
                return ResourceManager.GetString("Breastplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made of interlocking metal rings, chain mail includes a layer of quilted fabric worn underneath the mail to prevent chafing and to cushion the impact of blows. The suit includes gauntlets..
        /// </summary>
        internal static string ChainMail {
            get {
                return ResourceManager.GetString("ChainMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made of interlocking metal rings, a chain shirt is worn between layers of clothing or leather. This armor offers modest protection to the wearer’s upper body and allows the sound of the rings rubbing against one another to be muffled by outer layers..
        /// </summary>
        internal static string ChainShirt {
            get {
                return ResourceManager.GetString("ChainShirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half plate consists of shaped metal plates that cover most of the wearer’s body. It does not include leg protection beyond simple greaves that are attached with leather straps.
        /// </summary>
        internal static string HalfPlate {
            get {
                return ResourceManager.GetString("HalfPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This crude armor consists of thick furs and pelts. It is commonly worn by barbarian tribes, evil humanoids, and other folk who lack access to the tools and materials needed to create better armor..
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The breastplate and shoulder protectors of this armor are made of leather that has been stiffened by being boiled in oil. The rest of the armor is made of softer and more flexible materials..
        /// </summary>
        internal static string Leather {
            get {
                return ResourceManager.GetString("Leather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padded armor consists of quilted layers of cloth and batting..
        /// </summary>
        internal static string Padded {
            get {
                return ResourceManager.GetString("Padded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate consists of shaped, interlocking metal plates to cover the entire body. A suit of plate includes gauntlets, heavy leather boots, a visored helmet, and thick layers of padding underneath the armor. Buckles and straps distribute the weight over the body..
        /// </summary>
        internal static string Plate {
            get {
                return ResourceManager.GetString("Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This armor is leather armor with heavy rings sewn into it. The rings help reinforce the armor against blows from swords and axes. Ring mail is inferior to chain mail, and it&apos;s usually worn only by those who can’t afford better armor..
        /// </summary>
        internal static string RingMail {
            get {
                return ResourceManager.GetString("RingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This armor consists of a coat and leggings (and perhaps a separate skirt) of leather covered with overlapping pieces of metal, much like the scales of a fish. The suit includes gauntlets..
        /// </summary>
        internal static string ScaleMail {
            get {
                return ResourceManager.GetString("ScaleMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A shield is made from wood or metal and is carried in one hand. Wielding a shield increases your Armor Class by 2. You can benefit from only one shield at a time..
        /// </summary>
        internal static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This armor is made of narrow vertical strips of metal riveted to a backing of leather that is worn over cloth padding. Flexible chain mail protects the joints..
        /// </summary>
        internal static string Splint {
            get {
                return ResourceManager.GetString("Splint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made from tough but flexible leather, studded leather is reinforced with close-set rivets or spikes..
        /// </summary>
        internal static string StuddedLeather {
            get {
                return ResourceManager.GetString("StuddedLeather", resourceCulture);
            }
        }
    }
}
