//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Warlock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureWarlockText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureWarlockText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Warlock.FeatureWarlockText", typeof(FeatureWarlockText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature..
        /// </summary>
        internal static string Ability_Score_Improvement {
            get {
                return ResourceManager.GetString("Ability Score Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In your study of occult lore, you have unearthed eldritch invocations, fragments of forbidden knowledge that imbue you with an abiding magical ability.
        ///At 2nd level, you gain two eldritch invocations of your choice. When you gain certain warlock levels, you gain additional invocations of your choice, as shown in the Invocations Known column of the Warlock table.
        ///Additionally, when you gain a level in this class, you can choose one of the invocations you know and replace it with another invocation that you [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eldritch_Invocations {
            get {
                return ResourceManager.GetString("Eldritch Invocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 20th level, you can draw on your inner reserve of mystical power while entreating your patron to regain expended spell slots. You can spend 1 minute entreating your patron for aid to regain all your expended spell slots from your Pact Magic feature. Once you regain spell slots with this feature, you must finish a long rest before you can do so again..
        /// </summary>
        internal static string Eldritch_Master {
            get {
                return ResourceManager.GetString("Eldritch Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 11th level, your patron bestows upon you a magical secret called an arcanum. Choose one 6th-level spell from the warlock spell list as this arcanum.
        ///You can cast your arcanum spell once without expending a spell slot. You must finish a long rest before you can do so again.
        ///At higher levels, you gain more warlock spells of your choice that can be cast in this way: one 7th-level spell at 13th level, one 8th-level spell at 15th level, and one 9th-level spell at 17th level. You regain all uses of your Myst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mystic_Arcanum {
            get {
                return ResourceManager.GetString("Mystic Arcanum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 1st level, you have struck a bargain with an otherworldly being of your choice. Your choice grants you features at 1st level and again at 6th, 10th, and 14th level..
        /// </summary>
        internal static string Otherworldly_Patron {
            get {
                return ResourceManager.GetString("Otherworldly Patron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 3rd level, your otherworldly patron bestows a gift upon you for your loyal service. You gain one of the following featuresof your choice.
        ///
        /// Pact of the Chain
        ///You learn the find familiar spell and can cast it as a ritual. The spell doesn’t count against your number of spells known.
        ///When you cast the spell, you can choose one of the normal forms for your familiar or one of the following special forms: imp, pseudodragon, quasit, or sprite.
        ///Additionally, when you take the Attack action, you can forgo on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pact_Boon {
            get {
                return ResourceManager.GetString("Pact Boon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to create a pact weapon in your empty hand. You can choose the form that this melee weapon takes each time you create it. You are proficient with it while you wield it. This weapon counts as magical for the purpose of overcoming resistance and immunity to nonmagical attacks and damage.
        ///Your pact weapon disappears if it is more than 5 feet away from you for 1 minute or more. It also disappears if you use this feature again, if you dismiss the weapon (no action required), or if you di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pact_Boon__Pact_of_the_Blade {
            get {
                return ResourceManager.GetString("Pact Boon: Pact of the Blade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You learn the find familiar spell and can cast it as a ritual. The spell doesn’t count against your number of spells known.
        ///When you cast the spell, you can choose one of the normal forms for your familiar or one of the following special forms: imp, pseudodragon, quasit, or sprite.
        ///Additionally, when you take the Attack action, you can forgo one of your own attacks to allow your familiar to make one attack of its own with its reaction..
        /// </summary>
        internal static string Pact_Boon__Pact_of_the_Chain {
            get {
                return ResourceManager.GetString("Pact Boon: Pact of the Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your patron gives you a grimoire called a Book of Shadows. When you gain this feature, choose three cantrips from any class’s spell list (the three needn’t be from the same list). While the book is on your person, you can cast those cantrips at will. They don’t count against your number of cantrips known. If they don’t appear on the warlock spell list, they are nonetheless warlock spells for you.
        ///If you lose your Book of Shadows, you can perform a 1-hour ceremony to receive a replacement from your patron.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pact_Boon__Pact_of_the_Tome {
            get {
                return ResourceManager.GetString("Pact Boon: Pact of the Tome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your arcane research and the magic bestowed on you by your patron have given you facility with spells.
        ///
        /// Cantrips
        ///You know two cantrips of your choice from the warlock spell list. You learn additional warlock cantrips of your choice at higher levels, as shown in the Cantrips Known column of the Warlock table.
        ///
        /// Spell Slots
        ///The Warlock table shows how many spell slots you have. The table also shows what the level of those slots is; all of your spell slots are the same level. To cast one of your warlock [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pact_Magic {
            get {
                return ResourceManager.GetString("Pact Magic", resourceCulture);
            }
        }
    }
}
