//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Rogue.Thief {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureRogueThiefText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureRogueThiefText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Rogue.Thief.FeatureRogueThiefText", typeof(FeatureRogueThiefText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 3rd level, you can use the bonus action granted by your Cunning Action to make a Dexterity (Sleight of Hand) check, use your thieves’ tools to disarm a trap or open a lock, or take the Use an Object action..
        /// </summary>
        internal static string Fast_Hands {
            get {
                return ResourceManager.GetString("Fast Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you choose this archetype at 3rd level, you gain the ability to climb faster than normal; climbing no longer costs you extra movement.
        ///In addition, when you make a running jump, the distance you cover increases by a number of feet equal to your Dexterity modifier..
        /// </summary>
        internal static string Second_Story_Work {
            get {
                return ResourceManager.GetString("Second-Story Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 9th level, you have advantage on a Dexterity (Stealth) check if you move no more than half your speed on the same turn..
        /// </summary>
        internal static string Supreme_Sneak {
            get {
                return ResourceManager.GetString("Supreme Sneak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 17th level, you have become adept at laying ambushes and quickly escaping danger. You can take two turns during the first round of any combat. You take your first turn at your normal initiative and your second turn at your initiative minus 10. You can’t use this feature when you are surprised..
        /// </summary>
        internal static string Theif_s_Reflexes {
            get {
                return ResourceManager.GetString("Theif\'s Reflexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You hone your skills in the larcenous arts. Burglars, bandits, cutpurses, and other criminals typically follow this archetype, but so do rogues who prefer to think of themselves as professional treasure seekers, explorers, delvers, and investigators. In addition to improving your agility and stealth, you learn skills useful for delving into ancient ruins, reading unfamiliar languages, and using magic items you normally couldn’t employ..
        /// </summary>
        internal static string Thief {
            get {
                return ResourceManager.GetString("Thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By 13th level, you have learned enough about the workings of magic that you can improvise the use of items even when they are not intended for you. You ignore all class, race, and level requirements on the use of magic items..
        /// </summary>
        internal static string Use_Magic_Device {
            get {
                return ResourceManager.GetString("Use Magic Device", resourceCulture);
            }
        }
    }
}
