//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Ranger.Hunter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureRangerHunterText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureRangerHunterText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Ranger.Hunter.FeatureRangerHunterText", typeof(FeatureRangerHunterText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 7th level,you gain one of the following features of your choice.
        /// Escape the Horde. Opportunity attacks against you are made with disadvantage.
        /// Multiattack Defense. When a creature hits you with an attack, you gain a +4 bonus to AC against all subsequent attacks made by that creature for the rest of the turn.
        /// Steel Will. You have advantage on saving throws against being frightened..
        /// </summary>
        internal static string Defensive_Tactics {
            get {
                return ResourceManager.GetString("Defensive Tactics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity attacks against you are made with disadvantage..
        /// </summary>
        internal static string Defensive_Tactics__Escape_the_Horde {
            get {
                return ResourceManager.GetString("Defensive Tactics: Escape the Horde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a creature hits you with an attack, you gain a +4 bonus to AC against all subsequent attacks made by that creature for the rest of the turn..
        /// </summary>
        internal static string Defensive_Tactics__Multiattack_Defense {
            get {
                return ResourceManager.GetString("Defensive Tactics: Multiattack Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have advantage on saving throws against being frightened..
        /// </summary>
        internal static string Defensive_Tactics__Steel_Will {
            get {
                return ResourceManager.GetString("Defensive Tactics: Steel Will", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulating the Hunter archetype means accepting your place as a bulwark between civilization and the terrors of the wilderness. As you walk the Hunter’s path, you learn specialized techniques for fighting the threats you face, from rampaging ogres and hordes of orcs to towering giants and terrifying dragons..
        /// </summary>
        internal static string Hunter {
            get {
                return ResourceManager.GetString("Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 3rd level, you gain one of the following features of your choice.
        /// Colossus Slayer. Your tenacity can wear down the most potent foes. When you hit a creature with a weapon attack, the creature takes an extra 1d8 damage if it’s below its hit point maximum. You can deal this extradamage only once per turn.
        /// Giant Killer. When a Large or larger creature within 5 feet of you hits or misses you with an attack, you can use your reaction to attack that creature immediately after its attack, provided that you  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hunter_s_Prey {
            get {
                return ResourceManager.GetString("Hunter\'s Prey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your tenacity can wear down the most potent foes. When you hit a creature with a weapon attack, the creature takes an extra 1d8 damage if it’s below its hit point maximum. You can deal this extradamage only once per turn..
        /// </summary>
        internal static string Hunter_s_Prey__Colossus_Slayer {
            get {
                return ResourceManager.GetString("Hunter\'s Prey: Colossus Slayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a Large or larger creature within 5 feet of you hits or misses you with an attack, you can use your reaction to attack that creature immediately after its attack, provided that you can see the creature..
        /// </summary>
        internal static string Hunter_s_Prey__Giant_Killer {
            get {
                return ResourceManager.GetString("Hunter\'s Prey: Giant Killer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once on each of your turns when you make a weapon attack, you can make another attack with the same weapon against a different creature that is within 5 feet of the original target and within range of your weapon..
        /// </summary>
        internal static string Hunter_s_Prey__Horde_Breaker {
            get {
                return ResourceManager.GetString("Hunter\'s Prey: Horde Breaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 11th level, you gain one of the following features of your choice.
        /// Volley. You can use your action to make a ranged attack against any number of creatures within 10 feet of a point you can see within your weapon’s range. You must have ammunition for each target, as normal, and you make a separate attack roll for each target.
        /// Whirlwind Attack. You can use your action to make a melee attack against any number of creatures within 5 feet of you, with a separate attack roll for each target..
        /// </summary>
        internal static string Multiattack {
            get {
                return ResourceManager.GetString("Multiattack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to make a ranged attack against any number of creatures within 10 feet of a point you can see within your weapon’s range. You must have ammunition for each target, as normal, and you make a separate attack roll for each target..
        /// </summary>
        internal static string Multiattack__Volley {
            get {
                return ResourceManager.GetString("Multiattack: Volley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your action to make a melee attack against any number of creatures within 5 feet of you, with a separate attack roll for each target..
        /// </summary>
        internal static string Multiattack__Whirlwind_Attack {
            get {
                return ResourceManager.GetString("Multiattack: Whirlwind Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 15th level, you gain one of the following features of your choice.
        /// Evasion. When you are subjected to an effect, such as a red dragon’s fiery breath or a lightning boltspell, that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw, and only half damage if you fail.
        /// Stand Against the Tide. When a hostile creature misses you with a melee attack, you can use your reaction to force that creature to repeat the same attack aga [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Superior_Hunter_s_Defense {
            get {
                return ResourceManager.GetString("Superior Hunter\'s Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you are subjected to an effect, such as a red dragon’s fiery breath or a lightning boltspell, that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw, and only half damage if you fail..
        /// </summary>
        internal static string Superior_Hunter_s_Defense__Evasion {
            get {
                return ResourceManager.GetString("Superior Hunter\'s Defense: Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a hostile creature misses you with a melee attack, you can use your reaction to force that creature to repeat the same attack against another creature (other than itself) of your choice..
        /// </summary>
        internal static string Superior_Hunter_s_Defense__Stand_Against_the_Tide {
            get {
                return ResourceManager.GetString("Superior Hunter\'s Defense: Stand Against the Tide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an attacker that you can see hits you with an attack, you can use your reaction to halve the attack’s damage against you..
        /// </summary>
        internal static string Superior_Hunter_s_Defense__Uncanny_Dodge {
            get {
                return ResourceManager.GetString("Superior Hunter\'s Defense: Uncanny Dodge", resourceCulture);
            }
        }
    }
}
