//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Sorcerer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureSorcererText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureSorcererText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Sorcerer.FeatureSorcererText", typeof(FeatureSorcererText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature..
        /// </summary>
        internal static string Ability_Score_Improvement {
            get {
                return ResourceManager.GetString("Ability Score Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 2nd level, you tap into a deep wellspring of magic within yourself. This wellspring is represented by sorcery points, which allow you to create a variety of magical effects.
        ///
        /// Sorcery Points
        ///You have 2 sorcery points, and you gain more as you reach higher levels, as shown in the Sorcery Points column of the Sorcerer table. You can never have more sorcery points than shown on the table for your level. You regain all spent sorcery points when you finish a longrest.
        ///
        /// Flexible Casting
        ///You can use your [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Font_of_Magic {
            get {
                return ResourceManager.GetString("Font of Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 3rd level, you gain the ability to twist your spells to suit your needs. You gain two of the following Metamagic options of your choice. You gain another one at 10th and 17th level.
        ///You can use only one Metamagic option on a spell when you cast it, unless otherwise noted.
        ///
        /// Careful Spell
        ///When you cast a spell that forces other creatures to make a saving throw, you can protect some of those creatures from the spell’s full force. To do so, you spend 1 sorcery point and choose a number of those creature [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Metamagic {
            get {
                return ResourceManager.GetString("Metamagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you cast a spell that forces other creatures to make a saving throw, you can protect some of those creatures from the spell’s full force. To do so, you spend 1 sorcery point and choose a number of those creatures up to your Charisma modifier (minimum of one creature). A chosen creature automatically succeeds on its saving throw against the spell..
        /// </summary>
        internal static string Metamagic__Careful_Spell {
            get {
                return ResourceManager.GetString("Metamagic: Careful Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you cast a spell that has a range of 5 feet or greater, you can spend 1 sorcery point to double the range of the spell.
        ///When you cast a spell that has a range of touch, you can spend 1 sorcery point to make the range of thespell 30 feet..
        /// </summary>
        internal static string Metamagic__Distant_Spell {
            get {
                return ResourceManager.GetString("Metamagic: Distant Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you roll damage for a spell, you can spend 1 sorcery point to reroll a number of the damage dice up to your Charisma modifier (minimum of one). You must use the new rolls.
        ///You can use Empowered Spell even if you have already used a different Metamagic option during the casting of the spell..
        /// </summary>
        internal static string Metamagic__Empowered_Spell {
            get {
                return ResourceManager.GetString("Metamagic: Empowered Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you cast a spell that has a duration of 1 minute or longer, you can spend 1 sorcery point to double its duration, to a maximum duration of 24 hours..
        /// </summary>
        internal static string Metamagic__Extended_Spell {
            get {
                return ResourceManager.GetString("Metamagic: Extended Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you cast a spell that forces a creature to make a saving throw to resist its effects, you can spend 3 sorcery points to give one target of the spell disadvantage on its first saving throw made against the spell..
        /// </summary>
        internal static string Metamagic__Heightened_Spell {
            get {
                return ResourceManager.GetString("Metamagic: Heightened Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you cast a spell that has a casting time of 1 action, you can spend 2 sorcery points to change the casting time to 1 bonus action for this casting..
        /// </summary>
        internal static string Metamagic__Quickened_Spell {
            get {
                return ResourceManager.GetString("Metamagic: Quickened Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you cast a spell, you can spend 1 sorcery point to cast it without any somatic or verbal components..
        /// </summary>
        internal static string Metamagic__Subtle_Spell {
            get {
                return ResourceManager.GetString("Metamagic: Subtle Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you cast a spell that targets only one creature and doesn’t have a range of self, you can spend a number of sorcery points equal to the spell’s level to target a second creature in range with the same spell (1 sorcery point if the spell is a cantrip).
        ///To be eligible, a spell must be incapable of targeting more than one creature at the spell’s current level. For example, magic missileand scorching rayaren’t eligible, but ray of frostis..
        /// </summary>
        internal static string Metamagic__Twinned_Spell {
            get {
                return ResourceManager.GetString("Metamagic: Twinned Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a sorcerous origin, which describes the source of your innate magical power.
        ///Your choice grants you features when you choose it at 1st level and again at 6th, 14th, and 18th level..
        /// </summary>
        internal static string Sorcerous_Origin {
            get {
                return ResourceManager.GetString("Sorcerous Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 20th level, you regain 4 expended sorcery points whenever you finish a short rest..
        /// </summary>
        internal static string Sorcerous_Restoration {
            get {
                return ResourceManager.GetString("Sorcerous Restoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An event in your past, or in the life of a parent or ancestor, left an indelible mark on you, infusing you with arcane magic. This font of magic, whatever its origin, fuels your spells.
        ///
        /// Cantrips
        ///At 1st level, you know four cantrips of your choice from thesorcerer spell list. You learn additional sorcerer cantrips of your choice at higher levels, as shown in the Cantrips Known column of the Sorcerer table.
        ///
        /// Spell Slots
        ///The Sorcerer table shows how many spell slots you have to cast your spells of 1st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spellcasting {
            get {
                return ResourceManager.GetString("Spellcasting", resourceCulture);
            }
        }
    }
}
