//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Druid.CircleOfTheLand {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureDruidCircleOfTheLandText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureDruidCircleOfTheLandText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Druid.CircleOfTheLand.FeatureDruidCircleOfT" +
                            "heLandText", typeof(FeatureDruidCircleOfTheLandText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you choose this circle at 2nd level, you learn one additional druid cantrip of your choice..
        /// </summary>
        internal static string Bonus_Cantrip {
            get {
                return ResourceManager.GetString("Bonus Cantrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Circle of the Land is made up of mystics and sages who safeguard ancient knowledge and rites through a vast oral tradition. These druids meet within sacred circles of trees or standing stones to whisper primal secrets in Druidic. The circle’s wisest members preside as the chief priests of communities that holdto the Old Faith and serve as advisors to the rulers of those folk. As a member of this circle, your magic is influenced by the land where you were initiated into the circle’s mysterious rites..
        /// </summary>
        internal static string Circle_of_the_Land {
            get {
                return ResourceManager.GetString("Circle of the Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mystical connection to the land infuses you with the ability to cast certain spells. At 3rd, 5th, 7th, and 9th level you gain access to circle spells connected to the land where you became a druid. Choose that land—arctic, coast, desert, forest, grassland, mountain, or swamp—and consult the associated list of spells.
        ///Once you gain access to a circle spell, you always have it prepared, and it doesn’t count against the number of spells you can prepare each day. If you gain access to a spell that doesn’t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Circle_Spells {
            get {
                return ResourceManager.GetString("Circle Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 6th level, moving through nonmagical difficult terrain costs you no extra movement. You can also pass through nonmagical plants without being slowed by them and without taking damage from them if they have thorns, spines, or a similar hazard.
        ///In addition, you have advantage on saving throws against plants that are magically created or manipulated to impede movement, such those created by the entangle spell..
        /// </summary>
        internal static string Lands_Stride {
            get {
                return ResourceManager.GetString("Lands Stride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 2nd level, you can regain some of your magical energy by sitting in meditation and communing with nature. During a short rest, you choose expended spell slots to recover. The spell slots can have a combined level that is equal to or less than half your druid level (rounded up), and none of the slots can be 6th level or higher. You can’t use this feature again until you finish a long rest.
        ///For example, when you are a 4th-level druid, you can recover up to two levels worth of spell slots. You can [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Natural_Recovery {
            get {
                return ResourceManager.GetString("Natural Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 14th level, creatures of thenatural world sense your connection to nature and become hesitant to attack you. When a beast or plant creature attacks you, that creature must make a Wisdom saving throw against your druid spell save DC. On a failed save, the creature must choose a different target, or the attack automatically misses. On a successful save, the creature is immune to this effect for 24 hours.
        ///The creature is aware of this effect before it makes its attack against you..
        /// </summary>
        internal static string Natures_Sanctuary {
            get {
                return ResourceManager.GetString("Natures Sanctuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 10th level, you can’t be charmed or frightened by elementals or fey, and you are immune to poison and disease..
        /// </summary>
        internal static string Natures_Ward {
            get {
                return ResourceManager.GetString("Natures Ward", resourceCulture);
            }
        }
    }
}
