//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.Class.Fighter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureFighterText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureFighterText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.Class.Fighter.FeatureFighterText", typeof(FeatureFighterText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 2nd leveI, you can push yourself beyond your normal limits for a moment. On your turn, you can take
        ///one additional action on top of your regular action and a possible bonus action. Once you use this feature, you must finish a short or
        ///long rest before you can use it again.\nStarting at 17th level, you can use it twice before a rest, but only once on
        ///the same turn..
        /// </summary>
        internal static string ActionSurge {
            get {
                return ResourceManager.GetString("ActionSurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You adopt a particular style of fighting as your specialty. Choose one of the following options (Archery, Defense, Dueling, Great Weapon Fighting, Protection, Two-Weapon Fighting). You can&apos;t take a Fighting Style option more than once, even if you later get to choose again..
        /// </summary>
        internal static string FightingStyle {
            get {
                return ResourceManager.GetString("FightingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a limited well of stamina that you can draw on to protect yourself from harm. On your turn, you can use
        ///a bonus action to regain hit points equal to 1d10 + your fighter leveI. Once you use this feature, you must finish a short or
        ///long rest before you can use it again..
        /// </summary>
        internal static string SecondWind {
            get {
                return ResourceManager.GetString("SecondWind", resourceCulture);
            }
        }
    }
}
