//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Paladin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeaturePaladinText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeaturePaladinText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Paladin.FeaturePaladinText", typeof(FeaturePaladinText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature..
        /// </summary>
        internal static string Ability_Score_Improvement {
            get {
                return ResourceManager.GetString("Ability Score Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 10th level, you and friendly creatures within 10 feet of you can’t be frightened while you are conscious.
        ///At 18th level, the range of this aura increases to 30 feet..
        /// </summary>
        internal static string Aura_of_Courage {
            get {
                return ResourceManager.GetString("Aura of Courage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 6th level, whenever you or a friendly creature within 10 feet of you must make a saving throw, the creature gains a bonus to the saving throw equal to your Charisma modifier (with a minimum bonus of +1). You must be conscious to grant this bonus.
        ///At 18th level, the range of this aura increases to 30 feet..
        /// </summary>
        internal static string Aura_of_Protection {
            get {
                return ResourceManager.GetString("Aura of Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 14th level, you can use your action to end one spell on yourself or on one willing creature that you touch.
        ///You can use this feature a number of times equal to your Charisma modifier (a minimum of once). You regain expended uses when you finish a long rest..
        /// </summary>
        internal static string Cleansing_Touch {
            get {
                return ResourceManager.GetString("Cleansing Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By 3rd level, the divine magic flowing through you makes you immune to disease..
        /// </summary>
        internal static string Divine_Health {
            get {
                return ResourceManager.GetString("Divine Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The presence of strong evil registers on your senses like a noxious odor, and powerful good rings like heavenly music in your ears. As an action, you can open your awareness to detect such forces. Until the end of your next turn, you know the location of any celestial, fiend, or undead within 60 feet of you that is not behind total cover. You know the type (celestial, fiend, or undead) of any being whose presence you sense, but not its identity (the vampire Count Strahd von Zarovich, for instance). Within t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Divine_Sense {
            get {
                return ResourceManager.GetString("Divine Sense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 2nd level, when you hit a creature with a melee weapon attack, you can expend one spell slot to deal radiant damage to the target, in addition to the weapon’s damage. The extra damage is 2d8 for a 1st-level spell slot, plus 1d8 for each spell level higher than 1st, to a maximum of 5d8. The damage increases by 1d8 if the target is an undead or a fiend..
        /// </summary>
        internal static string Divine_Smite {
            get {
                return ResourceManager.GetString("Divine Smite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn..
        /// </summary>
        internal static string Extra_Attack {
            get {
                return ResourceManager.GetString("Extra Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 2nd level, you adopt a style of fighting as your specialty. Choose one of the following options. You can’t take a Fighting Style option more than once, even if you later get to choose again..
        /// </summary>
        internal static string Fighting_Style {
            get {
                return ResourceManager.GetString("Fighting Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By 11th level, you are so suffused with righteous might that all your melee weapon strikes carry divine power with them. Whenever you hit a creature with a melee weapon, the creature takes an extra 1d8 radiant damage. If you also use your Divine Smite with an attack, you add this damage to the extra damage of your Divine Smite..
        /// </summary>
        internal static string Improved_Divine_Smite {
            get {
                return ResourceManager.GetString("Improved Divine Smite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your blessed touch can heal wounds. You have a pool of healing power that replenishes when you take a long rest. With that pool, you can restore a total number of hit points equal to your paladin level × 5.
        ///As an action, you can touch a creature and draw power from the pool to restore a number of hit points to that creature, up to the maximum amount remaining in your pool.
        ///Alternatively, you can expend 5 hit points from your pool of healing to cure the target of one diseaseor neutralize one poison affecti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lay_on_Hands {
            get {
                return ResourceManager.GetString("Lay on Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 3rd level, you swear the oath that binds you as a paladin forever. Up to this time you have been in a preparatory stage, committed to the path but not yet sworn to it. Now you choose an oath, such as the Oath of Devotion.
        ///Your choice grants you features at 3rd level and again at 7th, 15th, and 20th level. Those features include oath spells and the Channel Divinity feature.
        ///
        /// Oath Spells
        ///Each oath has a list of associated spells. You gain access to these spells at the levels specified in t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sacred_Oath {
            get {
                return ResourceManager.GetString("Sacred Oath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By 2nd level, you have learned to draw on divine magic through meditation and prayer to cast spells as a cleric does.
        ///
        /// Preparing and Casting Spells
        ///The Paladin table shows how many spell slots you have to cast your spells. To cast one of your paladin spells of 1st level or higher, you must expend a slot of the spell’s level or higher. You regain all expended spell slots when you finish a long rest.
        ///You prepare the list of paladin spells that are available for you to cast, choosing from the paladin spel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spellcasting {
            get {
                return ResourceManager.GetString("Spellcasting", resourceCulture);
            }
        }
    }
}
