//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotC.FifthEd.SRD.Features.PlayerClass.Barbarian {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureBarbarianText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureBarbarianText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotC.FifthEd.SRD.Features.PlayerClass.Barbarian.FeatureBarbarianText", typeof(FeatureBarbarianText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature..
        /// </summary>
        internal static string Ability_Score_Improvement {
            get {
                return ResourceManager.GetString("Ability Score Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 9th level, you can roll one additional weapon damage die when determining the extra damage for a critical hit with a melee attack.
        ///This increases to two additional dice at 13th level and three additional dice at 17th level..
        /// </summary>
        internal static string Brutal_Critical {
            get {
                return ResourceManager.GetString("Brutal Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 2nd level, you gain an uncanny sense of when things nearby aren’t as they should be, giving you an edge when you dodge away from danger.
        ///You have advantage on Dexterity saving throws against effects that you can see, such as traps and spells. To gain this benefit, you can’t be blinded, deafened, or incapacitated..
        /// </summary>
        internal static string Danger_Sense {
            get {
                return ResourceManager.GetString("Danger Sense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn..
        /// </summary>
        internal static string Extra_Attack {
            get {
                return ResourceManager.GetString("Extra Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 5th level, your speed increases by 10 feet while you aren’t wearing heavy armor..
        /// </summary>
        internal static string Fast_Movement {
            get {
                return ResourceManager.GetString("Fast Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By 7th level,your instincts are so honed that you have advantage on initiative rolls.
        ///Additionally, if you are surprised at the beginning of combat and aren’t incapacitated, you can act normally on your first turn, but only if you enter your rage before doing anything else on that turn..
        /// </summary>
        internal static string Feral_Instinct {
            get {
                return ResourceManager.GetString("Feral Instinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 18th level, if your total for a Strength check is less than your Strength score, you can use that score in place of the total..
        /// </summary>
        internal static string Indomitable_Might {
            get {
                return ResourceManager.GetString("Indomitable Might", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning at 15th level, your rage is so fierce that it ends early only if you fall unconscious or if you choose to end it..
        /// </summary>
        internal static string Persistent_Rage {
            get {
                return ResourceManager.GetString("Persistent Rage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 20th level, you embody the power ofthe wilds. Your Strength and Constitution scores increase by 4. Your maximum for those scores is now 24..
        /// </summary>
        internal static string Primal_Champion {
            get {
                return ResourceManager.GetString("Primal Champion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 3rd level, you choose a path that shapes the nature of your rage. Your choice grants you features at 3rd level and again at 6th, 10th, and 14th levels..
        /// </summary>
        internal static string Primal_Path {
            get {
                return ResourceManager.GetString("Primal Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In battle, you fight with primal ferocity. On your turn, you can enter a rage as a bonus action.
        ///While raging, you gain the following benefits if you aren’t wearing heavy armor:
        /// • You have advantage on Strength checks and Strength saving throws.
        /// • When you make a melee weapon attack using Strength, you gain a bonus to the damage roll that increases as you gain levels as a barbarian, at 1st level this bonus os +2. This damage increases to +3 at 9th level and increases again to +4 at 16th level.
        /// • You  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rage {
            get {
                return ResourceManager.GetString("Rage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 2nd level, you can throw aside all concern for defense to attack with fierce desperation. When you make your first attack on your turn, you can decide to attack recklessly. Doing so gives you advantage on melee weapon attack rolls using Strength during this turn, but attack rolls against you have advantage until your next turn..
        /// </summary>
        internal static string Reckless_Attack {
            get {
                return ResourceManager.GetString("Reckless Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at 11th level, your rage can keep you fighting despite grievous wounds. If you drop to 0 hit points while you’re raging and don’t die outright, you can make a DC 10 Constitution saving throw. If you succeed, you drop to 1 hit point instead.
        ///Each time you use this feature after the first, the DC increases by 5. When you finish a short or long rest, the DC resets to 10..
        /// </summary>
        internal static string Relentless_Rage {
            get {
                return ResourceManager.GetString("Relentless Rage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit..
        /// </summary>
        internal static string Unarmored_Defense {
            get {
                return ResourceManager.GetString("Unarmored Defense", resourceCulture);
            }
        }
    }
}
